In [ ]:
%run  tools/my_train.py  --finetune-from ./model_final.pth --model bisenetv2

In [1]:
#configを,cityscapes用に書き換えると，以下のコード(最初から学習)は実行できる．
python -m torch.distributed.launch --nproc_per_node=2 tools/train.py  --model bisenetv2 

SyntaxError: invalid syntax (<ipython-input-1-4843734ef9c2>, line 2)

signateを読み込むようにconfigを書き換えるとエラー．
- dataloaderを作る部分を書き換える  

finetuneするようにパスを追加すると，dataloaderの読み込みで止まる．

↑train.pyのmodelを読み込むとこを書き換えることで解決
dataloaderが上手くgpuにのってなかった？

In [ ]:
python -m torch.distributed.launch --nproc_per_node=2 tools/train.py --finetune-from ./model_final.pth --model bisenetv2 # or bisenetv

In [ ]:
path = "./train.txt"
with open(path, mode='w') as f:
    for i in range(0,2243):
        f.write("seg_train_images/train_{}.jpg,seg_train_annotations/train_{}.png\n".format(str(i).zfill(4), str(i).zfill(4)))

In [ ]:
import cv2
import matplotlib.pyplot as plt
img = cv2.imread("./datasets/signate/seg_train_annotations/train_0000.png",0)
plt.imshow(img)

In [36]:
%run tools/demo_signate.py --model bisenetv2 --weight-path ./res/model_2020_09_09_20_24.pth --img-path ./train_0000.jpg

[[  0   0 255]
 [193 214   0]
 [180   0 129]
 [255 121 166]
 [255   0   0]
 [ 65 166   1]
 [208 149   1]
 [255 255   0]
 [255 134   0]
 [  0 152 225]
 [  0 203 151]
 [ 85 255  50]
 [ 92 136 125]
 [ 69  47 142]
 [136  45  66]
 [  0 255 255]
 [215   0 255]
 [180 131 135]
 [ 82  99   0]
 [ 86  62  67]]
[[13 13 13 ...  9  9  9]
 [13 13 13 ...  9  9  9]
 [13 13 13 ...  9  9  9]
 ...
 [13 13 13 ... 13 13 13]
 [13 13 13 ... 13 13 13]
 [13 13 13 ... 13 13 13]]


In [2]:

labels_info_signate = [
    {"hasInstances": False, "category": "void", "catid": 0, "name": "unlabeled", "ignoreInEval": True, "id": 0, "color": [0, 0, 0], "trainId": 255},
    {"hasInstances": False, "category": "void", "catid": 0, "name": "ego vehicle", "ignoreInEval": True, "id": 1, "color": [0, 0, 0], "trainId": 255},
    {"hasInstances": False, "category": "void", "catid": 0, "name": "rectification border", "ignoreInEval": True, "id": 2, "color": [0, 0, 0], "trainId": 255},
    {"hasInstances": False, "category": "void", "catid": 0, "name": "out of roi", "ignoreInEval": True, "id": 3, "color": [0, 0, 0], "trainId": 255},
    {"hasInstances": False, "category": "void", "catid": 0, "name": "static", "ignoreInEval": True, "id": 4, "color": [0, 0, 0], "trainId": 255},
    {"hasInstances": False, "category": "void", "catid": 0, "name": "dynamic", "ignoreInEval": True, "id": 5, "color": [111, 74, 0], "trainId": 255},
    {"hasInstances": False, "category": "void", "catid": 0, "name": "ground", "ignoreInEval": True, "id": 6, "color": [81, 0, 81], "trainId": 255},
    {"hasInstances": False, "category": "flat", "catid": 1, "name": "road", "ignoreInEval": False, "id": 7, "color": [69, 47, 142], "trainId": 0},
    {"hasInstances": False, "category": "flat", "catid": 1, "name": "sidewalk", "ignoreInEval": False, "id": 8, "color": [0, 255, 255], "trainId": 1},
    {"hasInstances": False, "category": "flat", "catid": 1, "name": "parking", "ignoreInEval": True, "id": 9, "color": [69, 47, 142], "trainId": 255},
    {"hasInstances": False, "category": "flat", "catid": 1, "name": "rail track", "ignoreInEval": True, "id": 10, "color": [230, 150, 140], "trainId": 255},
    {"hasInstances": False, "category": "construction", "catid": 2, "name": "building", "ignoreInEval": False, "id": 11, "color": [0, 203, 151], "trainId": 2},
    {"hasInstances": False, "category": "construction", "catid": 2, "name": "wall", "ignoreInEval": False, "id": 12, "color": [92, 136, 125], "trainId": 3},
    {"hasInstances": False, "category": "construction", "catid": 2, "name": "fence", "ignoreInEval": False, "id": 13, "color": [92, 136, 125], "trainId": 4},
    {"hasInstances": False, "category": "construction", "catid": 2, "name": "guard rail", "ignoreInEval": True, "id": 14, "color": [92, 136, 125], "trainId": 255},
    {"hasInstances": False, "category": "construction", "catid": 2, "name": "bridge", "ignoreInEval": True, "id": 15, "color": [0, 203, 151], "trainId": 255},
    {"hasInstances": False, "category": "construction", "catid": 2, "name": "tunnel", "ignoreInEval": True, "id": 16, "color": [0, 203, 151], "trainId": 255},
    {"hasInstances": False, "category": "object", "catid": 3, "name": "pole", "ignoreInEval": False, "id": 17, "color": [180, 131, 135], "trainId": 5},
    {"hasInstances": False, "category": "object", "catid": 3, "name": "polegroup", "ignoreInEval": True, "id": 18, "color": [180, 131, 135], "trainId": 255},
    {"hasInstances": False, "category": "object", "catid": 3, "name": "traffic light", "ignoreInEval": False, "id": 19, "color": [255, 255, 0], "trainId": 6},
    {"hasInstances": False, "category": "object", "catid": 3, "name": "traffic sign", "ignoreInEval": False, "id": 20, "color": [255, 134, 0], "trainId": 7},
    {"hasInstances": False, "category": "nature", "catid": 4, "name": "vegetation", "ignoreInEval": False, "id": 21, "color": [85, 255, 50], "trainId": 8},
    {"hasInstances": False, "category": "nature", "catid": 4, "name": "terrain", "ignoreInEval": False, "id": 22, "color": [85, 255, 50], "trainId": 9},
    {"hasInstances": False, "category": "sky", "catid": 5, "name": "sky", "ignoreInEval": False, "id": 23, "color": [0, 152, 225], "trainId": 10},
    {"hasInstances": True, "category": "human", "catid": 6, "name": "person", "ignoreInEval": False, "id": 24, "color": [255, 0, 0], "trainId": 11},
    {"hasInstances": True, "category": "human", "catid": 6, "name": "rider", "ignoreInEval": False, "id": 25, "color": [208, 149, 1], "trainId": 12},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "car", "ignoreInEval": False, "id": 26, "color": [0, 0, 255], "trainId": 13},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "truck", "ignoreInEval": False, "id": 27, "color": [180, 0, 129], "trainId": 14},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "bus", "ignoreInEval": False, "id": 28, "color": [193, 214, 0], "trainId": 15},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "caravan", "ignoreInEval": True, "id": 29, "color": [255, 121, 166], "trainId": 255},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "trailer", "ignoreInEval": True, "id": 30, "color": [255, 121, 166], "trainId": 255},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "train", "ignoreInEval": False, "id": 31, "color": [255, 121, 166], "trainId": 16},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "motorcycle", "ignoreInEval": False, "id": 32, "color": [65, 166, 1], "trainId": 17},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "bicycle", "ignoreInEval": False, "id": 33, "color": [208, 149, 1], "trainId": 18},
    {"hasInstances": False, "category": "vehicle", "catid": 7, "name": "license plate", "ignoreInEval": True, "id": -1, "color": [0, 0, 142], "trainId": -1}
]


In [3]:
labels_info_signate[0]["color"]

[0, 0, 0]

In [2]:
import numpy as np
import  cv2
palette = []
for i in range(len(labels_info_signate)):
    palette.append(labels_info_signate[i]["color"])

palette = np.array(palette, dtype=np.uint8)
palette = palette.reshape(-1,5,3)
palette_gray = cv2.cvtColor(palette, cv2.COLOR_RGB2GRAY)

print(palette_gray)

NameError: name 'labels_info_signate' is not defined

In [3]:
from tools.seg_codes.IOU import IOU
true = cv2.imread("./train_0000.png")
pred = cv2.imread("res.png")
IOU(true, pred)

TypeError: unhashable type: 'numpy.ndarray'

In [19]:
import numpy as np
import cv2
palette = [[0, 0, 255],
           [193, 214, 0],
           [180, 0, 129],
           [255, 121, 166],
           [255, 0, 0],
           [65, 166, 1],
           [208, 149, 1],
           [255, 255, 0],
           [255, 134, 0],
           [0, 152, 225],
           [0, 203, 151],
           [85, 255, 50],
           [92, 136, 125],
           [69, 47, 142],
           [136, 45, 66],
           [0, 255, 255],
           [215, 0, 255],
           [180, 131, 135],
           [81, 99, 0],
           [86, 62, 67]]
'''
label_name = [Car,
    Bus,
    Truck,
    SVehicle,
    Pedestrian,
    Motorbike,
    Bicycle,
    Signal,
    Signs,
    Sky,
    Building,
    Natural,
    Wall,
    Lane,
    Ground,
    Sidewalk,
    RoadShoulder,
    Obstacle, 
    others,
    own]
'''
palette = np.array(palette, dtype=np.uint8)
palette = palette.reshape(-1,5,3)
palette_gray = cv2.cvtColor(palette, cv2.COLOR_RGB2GRAY)
palette_gray = palette_gray.reshape(-1)
print(palette_gray)

[ 29 183  69 166  76 117 150 226 155 115 136 181 122  64  75 179  93 146
  82  70]


In [2]:
import numpy as np
city2sig_pallette = np.array([0, 70, 0, 0, 0,
                              0, 0, 64, 179, 0,
                              0, 136, 122, 122, 0,
                              0, 0, 146, 0, 226,
                              155, 181, 75, 115, 76,
                              117, 29, 69, 183, 0,
                              0, 82, 117, 150, 0, 0])
sig_pallette = np.array([ 29, 183,  69, 166,
 76, 117, 150, 226,
 155, 115, 136, 181,
 122,  64,  75, 179,
93, 146,  82,  70])

In [3]:
ans = []
for i in range(len(sig_pallette)):
    a = []
    for j in range(len(city2sig_pallette)):
        if sig_pallette[i] == city2sig_pallette[j]:
               a.append(j)
    ans.append(a) 
print(ans)

[[26], [28], [27], [], [24], [25, 32], [33], [19], [20], [23], [11], [21], [12, 13], [7], [22], [8], [], [17], [31], [1]]


In [15]:
import matplotlib.pyplot as plt
from PIL import Image, ImageOps, ImageFilter 
img = cv2.imread("./datasets/signate_dataset/seg_train_annotations/train_0000.png", 0)
print(img)
mask = Image.open("./datasets/signate_dataset/seg_train_annotations/train_0000.png").convert('L')
mask = np.asarray(mask)
print(mask)

[[136 136 136 ... 114 114 114]
 [136 136 136 ... 114 114 114]
 [136 136 136 ... 114 114 114]
 ...
 [ 69  69  69 ...  69  69  69]
 [ 69  69  69 ...  69  69  69]
 [ 69  69  69 ...  69  69  69]]
[[136 136 136 ... 115 115 115]
 [136 136 136 ... 115 115 115]
 [136 136 136 ... 115 115 115]
 ...
 [ 70  70  70 ...  70  70  70]
 [ 70  70  70 ...  70  70  70]
 [ 70  70  70 ...  70  70  70]]


In [27]:
ans = np.full(255,255)
signate_pallette = [29, 183, 69, 166, 76,
                    117, 150, 226, 155, 115,
                    136, 181, 122,  64,  75,
                    179,  93, 146,  82,  70]
for i in range(len(ans)):
    for j in range(len(signate_pallette)):
        if i == signate_pallette[j]:
            ans[i] = j
ans

array([255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255,   0, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,  13,
       255, 255, 255, 255,   2,  19, 255, 255, 255, 255,  14,   4, 255,
       255, 255, 255, 255,  18, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255,  16, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,   9, 255,
         5, 255, 255, 255, 255,  12, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255,  10, 255, 255, 255, 255, 255, 255,
       255, 255, 255,  17, 255, 255, 255,   6, 255, 255, 255, 255,   8,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255,   3, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255,  15, 25

self.head = SegmentHead(128, 1024, n_classes)  
だけを初期化し，finetuneしてみる(初期化せずにやるより良さそう)  
15iter mIOU about 0.02  
150iter about mIOU 0.18    

In [37]:
#実行コードは以下(gpu2枚の場合)
#ターミナルで実行する
#python -m torch.distributed.launch --nproc_per_node=2 tools/train_from_signate.py --finetune-from ./model_final.pth --model bisenetv2